const items = [
  { title: "Echoes of Silence", tag: ["mix"], img: "./assets/img1.jpg" },
  { title: "Midnight Canvas", tag: ["design"], img: "./assets/img2.jpg" },
  { title: "Vibrant Rhythms", tag: ["music"], img: "./assets/img3.jpg" },
  { title: "Shadow Dance", tag: ["mix"], img: "./assets/img4.jpg" },
  { title: "Colorful Serenity", tag: ["design"], img: "./assets/img5.jpg" },
  { title: "Dream Weaver", tag: ["mix"], img: "./assets/img6.jpg" },
  { title: "Urban Mirage", tag: ["design"], img: "./assets/img7.jpg" },
  { title: "Sonic Bloom", tag: ["music"], img: "./assets/img8.jpg" },
  { title: "Celestial Nights", tag: ["mix"], img: "./assets/img9.jpg" },
  { title: "Harmony Quest", tag: ["music"], img: "./assets/img10.jpg" },
  { title: "Abstract Harmony", tag: ["design"], img: "./assets/img11.jpg" },
  { title: "Rhythm and Space", tag: ["mix"], img: "./assets/img12.jpg" },
  { title: "Ethereal Echoes", tag: ["music"], img: "./assets/img13.jpg" },
  { title: "Whispers of Twilight", tag: ["mix"], img: "./assets/img14.jpg" },
  { title: "Mosaic of Dreams", tag: ["design"], img: "./assets/img15.jpg" },
  { title: "Glimpse of Eternity", tag: ["mix"], img: "./assets/img16.jpg" },
  { title: "Infinite Palette", tag: ["mix"], img: "./assets/img17.jpg" },
  { title: "Soul's Resonance", tag: ["music"], img: "./assets/img18.jpg" },
  { title: "Spectral Designs", tag: ["design"], img: "./assets/img19.jpg" },
  { title: "Temporal Visions", tag: ["mix"], img: "./assets/img20.jpg" },
  { title: "Luminous Journey", tag: ["design"], img: "./assets/img21.jpg" },
  { title: "Melodic Horizon", tag: ["music"], img: "./assets/img22.jpg" },
  { title: "Eclipse of the Heart", tag: ["mix"], img: "./assets/img23.jpg" },
  { title: "Canvas of Sound", tag: ["design"], img: "./assets/img24.jpg" },
  { title: "Aurora's Whisper", tag: ["mix"], img: "./assets/img25.jpg" },
  { title: "Visions in Bloom", tag: ["design"], img: "./assets/img26.jpg" },
  { title: "Harmonious Disarray", tag: ["music"], img: "./assets/img27.jpg" },
  { title: "Orchestral Dreams", tag: ["music"], img: "./assets/img28.jpg" },
  { title: "Symphony of Night", tag: ["design"], img: "./assets/img29.jpg" },
  { title: "Echoing Serenade", tag: ["music"], img: "./assets/img30.jpg" },
  { title: "Mystical Frequencies", tag: ["mix"], img: "./assets/img31.jpg" },
  { title: "Serenity in Chaos", tag: ["mix"], img: "./assets/img32.jpg" },
  { title: "Rhythmic Illusions", tag: ["music"], img: "./assets/img33.jpg" },
  { title: "The Color of Sound", tag: ["design"], img: "./assets/img34.jpg" },
];
